### ISSUE TITLE
Fix pyarrow warning

### ISSUE THREAD

**Issue by birdsarah** [mozilla/dye-score#11]
```
UserWarning: pyarrow.open_stream is deprecated, please use pyarrow.ipc.open_stream
  warnings.warn("pyarrow.open_stream is deprecated, please use "
```

**Comment by birdsarah** [comment]
I haven't noticed this lately. Closing.

**Comment by kanchantewary** [comment]
I am getting the same warning while using the pyarrow 0.13 version, with pyspark 2.4. thoughts?

**Comment by birdsarah** [comment]
I have downgraded to 0.12.1 recently due to a compatibility error with Dask. This is probably why I haven't seen the error. I'll only be upgrading when a new version of pyarrow comes out, so I'll see what it's like then.

**Comment by kanchantewary** [comment]
Thanks Sarah. will try with 0.12.1.

Cheers,
Kanchan
